# Generated by Django 4.1.3 on 2022-11-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erasure', '0002_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=True, null=True, upload_to='text_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erasure.profile')),
            ],
        ),
    ]
