# Generated by Django 4.1.3 on 2022-11-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erasure', '0003_remove_profile_file_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='user',
            new_name='Profile',
        ),
    ]
